//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML-to-Markdown
//! conversion, and image processing.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/find/grep/html/highlight/image/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]

pub mod clipboard;
pub mod glob;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod image;
pub mod keys;
pub mod prof;
pub mod ps;
pub mod shell;
pub mod system_info;
pub mod task;
pub mod text;
